// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApQq5RihjCCQDVkI3ZpksIg5pX52kawDE',
    appId: '1:549363925222:web:88c26871419c3266743b27',
    messagingSenderId: '549363925222',
    projectId: 'offer-informing-app-184f5',
    authDomain: 'offer-informing-app-184f5.firebaseapp.com',
    storageBucket: 'offer-informing-app-184f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn1DN7h4FYQ8_ri94YOzGj27b8Ma9CtQk',
    appId: '1:549363925222:android:e29f4e6cfa0404c5743b27',
    messagingSenderId: '549363925222',
    projectId: 'offer-informing-app-184f5',
    storageBucket: 'offer-informing-app-184f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEc3VNq5-0o3d1-Dmw0sHnyyHzraaO09E',
    appId: '1:549363925222:ios:98d76bc7b0c76701743b27',
    messagingSenderId: '549363925222',
    projectId: 'offer-informing-app-184f5',
    storageBucket: 'offer-informing-app-184f5.appspot.com',
    iosBundleId: 'com.example.offerInformingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEc3VNq5-0o3d1-Dmw0sHnyyHzraaO09E',
    appId: '1:549363925222:ios:98d76bc7b0c76701743b27',
    messagingSenderId: '549363925222',
    projectId: 'offer-informing-app-184f5',
    storageBucket: 'offer-informing-app-184f5.appspot.com',
    iosBundleId: 'com.example.offerInformingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApQq5RihjCCQDVkI3ZpksIg5pX52kawDE',
    appId: '1:549363925222:web:c8d4957a5b2e14fa743b27',
    messagingSenderId: '549363925222',
    projectId: 'offer-informing-app-184f5',
    authDomain: 'offer-informing-app-184f5.firebaseapp.com',
    storageBucket: 'offer-informing-app-184f5.appspot.com',
  );
}
